### ISSUE TITLE
k-mer threshold parameter in dCNS maskGenome -f ?

### ISSUE THREAD

**Issue by margaretwoodhouse** [baoxingsong/dCNS#12]
Hi, Baoxing:

Using the ggplot2 code to pick the secondary derivate for the k-mer threshold from the .hist file for setaria, the result was 33. It looks like the parameter for -f is 33 for dCNS maskGenome:

`dCNS maskGenome -i Setaria_italica.Setaria_italica_v2.0.dna.toplevel.fa -o masked_setaria_k20_50.fa -s setaria.sam -c gene.fa -k setaria_k20_count_dumps.fa -f 33`

I just want to confirm that this is where we plug in the 2nd derivate k-mer threshold information, since it's not totally clear to me. Thanks!

**Comment by baoxingsong** [comment]
Yes, that is correct.
The 2nd derivate is an empirical pickup, there is no statistical theory underlying that choice.
Sorry for the document is not totally clear. If you have suggestions to improve the document to make it more clear, please let me know.

**Comment by margaretwoodhouse** [comment]
Great, thanks! The rest of the documentation is excellent; the program is very easy to install and run. My only suggestion is that, I think where you have the documentation where it says 

`"Currently, we use the sencondary drivate to pickup the threshold. (It maybe not the best solution. Other ideas are welcome to test.)"`

 perhaps you could say something like:

`"Currently, we use the sencondary drivate to pickup the threshold. (It maybe not the best solution. Other ideas are welcome to test.) This value will be used for the downstream dCNS maskGenome analysis for the parameter -f`

Or something like that? Thanks so much!
