### ISSUE TITLE
genomic coordinates for the query genome included in the sam file?

### ISSUE THREAD

**Issue by margaretwoodhouse** [baoxingsong/dCNS#14]
I'm planning to run dCNS on all the NAM founder lines in maize, and then compare PAV of CNSs across the lines. However, there isn't an easy way to do a comparison across maize lines vs the PAV of the query genomes, since the sam outputs don't include the coordinates of the query genome CNSs. Is there a way to include the query genome coordinates in the output file? I believe the code could be rewritten to subtract the alignment results from the flanking sequence in the query. For instance, if one of the input files has the fasta headers

```
>reference	Zm00042ab127520up	species:reference	chr:chr3	strand:1	start:19936255	end:19986254
>query	species:query	chr:Chr03	strand:1	start:6410498	end:6460497
```

then the query alignment results between query/reference can be subtracted from `query	species:query	chr:Chr03	strand:1	start:6410498	end:6460497` and that information included in the output bam file. Would that be possible to do? That way, it would be easy to directly compare the PAV of CNSs across maize lines to the query genome. I think this would also be very useful for other people who study CNSs in genomes with many sequenced cultivars. 

Thank you!

**Comment by baoxingsong** [comment]
Thanks for this suggestion.
The query genome coordinates are in the source code, but not in the SAM output file. Initially, I tried to output the query coordinate into the output SAM file, but that SAM file did not compatible with samtools.
I will look into that more carefully.

**Comment by margaretwoodhouse** [comment]
Oh ok, I see. Perhaps you could include a command on github to extract the query coordinates as well as the reference coordinates  and maybe have it formatted similar to a paf file or something like that, as an option (not as a replacement for the sam file)?  Thanks so much!
