### ISSUE TITLE
Can I use dCNS to idenetify CNS between Arabidopsis thaliana and Oryza sativa

### ISSUE THREAD

**Issue by shangguandong1996** [baoxingsong/dCNS#23]
Hi, Dr song
Thanks for your awesome tool. 
I find your example inlcuding Brassicaceae species, grass tribe Andropogoneae. But I am wondering whethter I can use dCNS to identify CNS between At and Os, or At, Os, maize.
If dCNS can work, Can I also use this [setting parameters manual](https://github.com/baoxingsong/dCNS/blob/master/docs/parameters.pdf) to set my parameters ?

Best wishes

Guandong Shang

**Comment by baoxingsong** [comment]
Thanks for your interest in our approach.

I did not test dCNS between Os and maize, but I do not have a reason why it would not work I think it deserves a try.

The phylogenetic distance between At and OS/maize is far, and the homologous genes between them are not in good collinearity. Thus I would like to interpret the dCNS results very carefully for them.

**Comment by shangguandong1996** [comment]
Thanks for your reply:)
I am sorry I do not understand the connect between "good gene collinearity" and "dCNS result". Because according to the pipeline in paper, it seems that "homologous genes between them are not in good collinearity" do not infulence the CNS identify.
Is it because At and Os do not have good gene collinearity, so minimap2 can not map the CDS sequence of reference to the query genome sequence well?

Please forgive me if I misunderstand something.

Best wishes

Guandong Shang

**Comment by baoxingsong** [comment]
Our genome research paper is mainly describing the results and did not explain the underlying assumptions in detail.

dCNS assumes cis-regulatory elements and target genes in good collinearity.

Homologous genes between At and Os are not in good collinearity, I am not sure cis-regulatory elements and target genes are still in good collinearity.

**Comment by shangguandong1996** [comment]
Thanks, I get it :)
